-- Tạo database VIET_SPORT
CREATE DATABASE VIET_SPORT;
GO

-- Chọn database VIET_SPORT
USE VIET_SPORT;
GO

-- Tạo bảng ACCOUNT_LOGIN
CREATE TABLE ACCOUNT_LOGIN (
  AccountLogin NVARCHAR(50) PRIMARY KEY,
  Password NVARCHAR(255)
);
GO

-- Tạo bảng SPORT_CENTER
CREATE TABLE SPORT_CENTER (
  CenterID NVARCHAR(50) PRIMARY KEY,
  Address NVARCHAR(255),
  Hotline NVARCHAR(20),
  OpenTime TIME,
  CloseTime TIME,
  Owner NVARCHAR(255)
);
GO

-- Tạo bảng EMPLOYEE
CREATE TABLE EMPLOYEE (
  EmployeeID NVARCHAR(50) PRIMARY KEY,
  FullName NVARCHAR(255),
  Birthday DATE,
  Gender NVARCHAR(10),
  CCCD NVARCHAR(20),
  Street NVARCHAR(255),
  District NVARCHAR(255),
  City NVARCHAR(255),
  PhoneNumber NVARCHAR(20),
  BasicSalary DECIMAL(10, 2),
  Manager NVARCHAR(50),
  CenterID NVARCHAR(50),
  AccountLogin NVARCHAR(50),
  IsManager INT,
  IsReceptionist INT,
  IsTechnician INT,
  IsCashier INT,
  IsAdmin INT,
  FOREIGN KEY (Manager) REFERENCES EMPLOYEE(EmployeeID),
  FOREIGN KEY (CenterID) REFERENCES SPORT_CENTER(CenterID),
  FOREIGN KEY (AccountLogin) REFERENCES ACCOUNT_LOGIN(AccountLogin)
);
GO 

-- Tạo bảng SYSTEM_PARAMETER
CREATE TABLE SYSTEM_PARAMETER (
  SystemPID NVARCHAR(50) PRIMARY KEY,
  SetupDate DATE,
  SetupTime TIME,
  Price DECIMAL(10, 2),
  MinBookingTime INT,
  MaxBookingTime INT,
  MaxCourtsPerCustomer INT,
  AID NVARCHAR(50),
  FOREIGN KEY (AID) REFERENCES EMPLOYEE(EmployeeID)
);
GO

-- Tạo bảng EMPLOYEE_SCHEDULE
CREATE TABLE EMPLOYEE_SCHEDULE (
	ScheduleID NVARCHAR(50) PRIMARY KEY,
	StartTime DATETIME,
	EndTime DATETIME
);
GO

-- Tạo bảng ATTENDANCE
CREATE TABLE ATTENDANCE (
  AttendanceID NVARCHAR(50) PRIMARY KEY,
  EmployeeID NVARCHAR(50),
  ScheduleID NVARCHAR(50),
  CheckIn DATETIME,
  CheckOut DATETIME,
  Status NVARCHAR(20),
  FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID),
  FOREIGN KEY (ScheduleID) REFERENCES EMPLOYEE_SCHEDULE(ScheduleID)
);
GO

-- Tạo bảng LEAVEFORM 
CREATE TABLE LEAVEFORM (
  LeaveFormID NVARCHAR(50) PRIMARY KEY,
  EmployeeID NVARCHAR(50),
  ScheduleID NVARCHAR(50),
  DateCreate DATETIME,
	Reason NVARCHAR(255),
  Status NVARCHAR(20),
  FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID),
	FOREIGN KEY (ScheduleID) REFERENCES EMPLOYEE_SCHEDULE(ScheduleID)
);
GO

-- Tạo bảng CUSTOMER
CREATE TABLE CUSTOMER (
  CustomerID NVARCHAR(50) PRIMARY KEY,
  FullName NVARCHAR(255),
  Birthday DATE,
  PhoneNumber NVARCHAR(20),
  Email NVARCHAR(50),
  Address NVARCHAR(255),
  IsOnline INT,
  IsDirectly INT,
  AccountLogin NVARCHAR(50),
  FOREIGN KEY (AccountLogin) REFERENCES ACCOUNT_LOGIN(AccountLogin)
);
GO

-- Tạo bảng COACH
CREATE TABLE COACH (
  CoachID NVARCHAR(50) PRIMARY KEY,
  FullName NVARCHAR(255),
  Specialization NVARCHAR(255),
  ScheduleWork NVARCHAR(255),
  Price DECIMAL(10, 2)
);
GO

--Tạo bảng COURT_TYPE
CREATE TABLE COURT_TYPE (
	CourtType NVARCHAR(50) PRIMARY KEY,
	TypeofRental NVARCHAR(255)
);
GO

--Tạo bảng SPORT_COURT 
CREATE TABLE SPORT_COURT(
	CourtID NVARCHAR(50) PRIMARY KEY,
	CourtType NVARCHAR(50),
	Capacity INT,
	UnitPrice DECIMAL(10,2),
	CenterID NVARCHAR(50),
	FOREIGN KEY (CourtType) REFERENCES COURT_TYPE(CourtType),
	FOREIGN KEY (CenterID) REFERENCES SPORT_CENTER(CenterID)
);
GO

-- Tạo bảng BOOKING_FORM
CREATE TABLE BOOKING_FORM (
  BookingID NVARCHAR(50) PRIMARY KEY,
  CourtID NVARCHAR(50),
  OrderDate DATE,
  OrderTime TIME,
  StartTime DATETIME,
  EndTime DATETIME,
  Status NVARCHAR(20),
  CustomerID NVARCHAR(50),
  SportCenterID NVARCHAR(50),
  RID NVARCHAR(50),
  FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID),
  FOREIGN KEY (SportCenterID) REFERENCES SPORT_CENTER(CenterID),
  FOREIGN KEY (RID) REFERENCES EMPLOYEE(EmployeeID),
  FOREIGN KEY (CourtID) REFERENCES SPORT_COURT(CourtID)
);
GO

-- Tạo bảng MEMBER_CARD
CREATE TABLE MEMBER_CARD (
  CardID NVARCHAR(50) PRIMARY KEY,
  MembershipLevel NVARCHAR(50),
  CustomerID NVARCHAR(50),
  FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID)
);
GO

-- Tạo bảng CANCEL_RULE
CREATE TABLE CANCEL_RULE (
    CancelRuleID NVARCHAR(50) PRIMARY KEY,
    RuleName NVARCHAR(100),
    MinimumTime INT,
    TimeUnit NVARCHAR(20),
	PenaltyFee DECIMAL(10,2),
	MID NVARCHAR(50),
	FOREIGN KEY (MID) REFERENCES EMPLOYEE(EmployeeID)
);
GO

-- Tạo bảng DISCOUNT
CREATE TABLE DISCOUNT (
  DiscountID NVARCHAR(50) PRIMARY KEY,
  DiscountName NVARCHAR(100),
  StartDate DATE,
  EndDate DATE,
  Percentage DECIMAL(10,2),
  TargetUser NVARCHAR(255),
  MID NVARCHAR(50),
  FOREIGN KEY (MID) REFERENCES EMPLOYEE(EmployeeID)
);
GO

--Tạo bảng PAYROLL
CREATE TABLE PAYROLL (
	PayrollID NVARCHAR(50) PRIMARY KEY,
	Month INT,
	Year INT,
	BasicSalary DECIMAL(10,2),
	Allowance DECIMAL(10,2),
	ShiftPay DECIMAL(10,2),
	SaleCommission DECIMAL(10,2),
	PenaltyFee DECIMAL(10,2),
	EmployeeID NVARCHAR(50),
	FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID)
);
GO

-- Tạo bảng INVOICE
CREATE TABLE INVOICE (
  InvoiceID NVARCHAR(50) PRIMARY KEY,
  RentTime DATETIME,
  TotalPrice DECIMAL(10, 2),
  PaymentMethod NVARCHAR(20),
  CreateTime DATETIME,
  Status NVARCHAR(50),
  BookingID NVARCHAR(50),
  DiscountID NVARCHAR(50),
  CourtID NVARCHAR(50),
  CID NVARCHAR(50),
  FOREIGN KEY (BookingID) REFERENCES BOOKING_FORM(BookingID),
  FOREIGN KEY (CourtID) REFERENCES SPORT_COURT(CourtID),
  FOREIGN KEY (DiscountID) REFERENCES DISCOUNT(DiscountID),
  FOREIGN KEY (CID) REFERENCES EMPLOYEE(EmployeeID)
);
GO

-- Tạo bảng CANCELLATION_FORM
CREATE TABLE CANCELLATION_FORM (
  CancelFormID NVARCHAR(50) PRIMARY KEY,
  CancelTime DATETIME,
  PenaltyPrice DECIMAL(10, 2),
  Status NVARCHAR(50),
  CancelRuleID NVARCHAR(50),
  BookingID NVARCHAR(50),
  FOREIGN KEY (CancelRuleID) REFERENCES CANCEL_RULE(CancelRuleID),
  FOREIGN KEY (BookingID) REFERENCES BOOKING_FORM(BookingID)
);
GO

-- Tạo bảng SERVICE 
CREATE TABLE SERVICE (
	ServiceID NVARCHAR(50) PRIMARY KEY,
	ServiceName NVARCHAR(255),
	TimeUnitType NVARCHAR(255),
	Price DECIMAL(10,2),
	AvailableStatus NVARCHAR(50)
);
GO

-- Tạo bảng SERVICE_BOOKING
CREATE TABLE SERVICE_BOOKING (
  SBID NVARCHAR(50) PRIMARY KEY,
  BookingID NVARCHAR(50),
  ServiceID NVARCHAR(50),
  BookingQuantity INT,
  FOREIGN KEY (BookingID) REFERENCES BOOKING_FORM(BookingID),
  FOREIGN KEY (ServiceID) REFERENCES SERVICE(ServiceID)
);
GO

-- Tạo bảng PERSONAL_CLOSET
CREATE TABLE PERSONAL_CLOSET (
  PCServiceID NVARCHAR(50) PRIMARY KEY,
  ClosetID INT,
  StatusCloset NVARCHAR(50),
  FOREIGN KEY (PCServiceID) REFERENCES SERVICE(ServiceID)
);
GO

-- Tạo bảng RENTING_EQUIPMENT
CREATE TABLE RENTING_EQUIPMENT (
  REServiceID NVARCHAR(50) PRIMARY KEY,
  EquipmentType NVARCHAR(50),
  Quantity INT,
  FOREIGN KEY (REServiceID) REFERENCES SERVICE(ServiceID)
);
GO

-- Tạo bảng VIP_ROOM
CREATE TABLE VIP_ROOM (
  VRServiceID NVARCHAR(50) PRIMARY KEY,
  RoomID INT,
  StatusRoom NVARCHAR(50),
  FOREIGN KEY (VRServiceID) REFERENCES SERVICE(ServiceID)
);
GO

-- Tạo bảng RENTING_HLV
CREATE TABLE RENTING_HLV (
  RHServiceID NVARCHAR(50) PRIMARY KEY,
  Status NVARCHAR(50),
  Coach NVARCHAR(50),
  FOREIGN KEY (RHServiceID) REFERENCES SERVICE(ServiceID),
  FOREIGN KEY (Coach) REFERENCES COACH(CoachID)
);
GO
