-- Tạo database SPORT_CENTER
CREATE DATABASE SPORT_CENTER;
GO

-- Chọn database SPORT_CENTER
USE SPORT_CENTER;
GO

-- Tạo bảng ACCOUNT_LOGIN
CREATE TABLE ACCOUNT_LOGIN (
  AccountLogin NVARCHAR(50) PRIMARY KEY,
  Password NVARCHAR(255)
);
GO

-- Tạo bảng SPORT_CENTER
CREATE TABLE SPORT_CENTER (
  CenterID INT PRIMARY KEY,
  Address NVARCHAR(255),
  Hotline NVARCHAR(20),
  OpenTime TIME,
  CloseTime TIME,
  Owner NVARCHAR(255)
);
GO

-- Tạo bảng EMPLOYEE
CREATE TABLE EMPLOYEE (
  EmployeeID INT PRIMARY KEY,
  FullName NVARCHAR(255),
  Birthday DATE,
  Gender NVARCHAR(10),
  CCCD NVARCHAR(20),
  Street NVARCHAR(255),
  District NVARCHAR(255),
  City NVARCHAR(255),
  PhoneNumber NVARCHAR(20),
  Role NVARCHAR(50),
  BasicSalary DECIMAL(10, 2),
  Manager INT,
  CenterID INT,
  AccountLogin NVARCHAR(50),
	IsManager INT,
	IsReceptionist INT,
	IsTechnician INT,
	IsCashier INT,
	IsAdmin INT,
	FOREIGN KEY (Manager) REFERENCES EMPLOYEE(EmployeeID),
	FOREIGN KEY (CenterID) REFERENCES SPORT_CENTER(CenterID),
	FOREIGN KEY (AccountLogin) REFERENCES ACCOUNT_LOGIN(AccountLogin)
);
GO 

-- Tạo bảng SYSTEM_PARAMETER
CREATE TABLE SYSTEM_PARAMETER (
  SystemPID INT PRIMARY KEY,
  SetupDate DATE,
  SetupTime TIME,
  Price DECIMAL(10, 2),
  MinBookingTime INT,
  MaxBookingTime INT,
  MaxCourtsPerCustomer INT,
	AID INT,
	FOREIGN KEY (AID) REFERENCES EMPLOYEE(EmployeeID)
);
GO

-- Tạo bảng EMPLOYEE_SCHEDULE
CREATE TABLE EMPLOYEE_SCHEDULE (
	ScheduleID INT PRIMARY KEY,
	StartTime DATETIME,
	EndTime DATETIME
);
GO

-- Tạo bảng ATTENDANCE
CREATE TABLE ATTENDANCE (
  AttendanceID INT PRIMARY KEY,
  EmployeeID INT,
  ScheduleID INT,
  CheckIn DATETIME,
  CheckOut DATETIME,
  Status NVARCHAR(20),
  FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID),
	FOREIGN KEY (ScheduleID) REFERENCES EMPLOYEE_SCHEDULE(ScheduleID)
);
GO

-- Tạo bảng LEAVEFORM 
CREATE TABLE LEAVEFORM (
  LeaveFormID INT PRIMARY KEY,
  EmployeeID INT,
  ScheduleID INT,
  DateCreate DATETIME,
	Reason NVARCHAR(255),
  Status NVARCHAR(20),
  FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID),
	FOREIGN KEY (ScheduleID) REFERENCES EMPLOYEE_SCHEDULE(ScheduleID)
);
GO

-- Tạo bảng CUSTOMER
CREATE TABLE CUSTOMER (
  CustomerID INT PRIMARY KEY,
  FullName NVARCHAR(255),
  Birthday DATE,
  PhoneNumber NVARCHAR(20),
	Email NVARCHAR(50),
	Address NVARCHAR(255),
	IsOnline INT,
	IsDirectly INT,
	AccountLogin NVARCHAR(50),
	FOREIGN KEY (AccountLogin) REFERENCES ACCOUNT_LOGIN(AccountLogin)
);
GO

-- Tạo bảng COACH
CREATE TABLE COACH (
  CoachID INT PRIMARY KEY,
  FullName NVARCHAR(255),
  Specialization NVARCHAR(255),
  ScheduleWork NVARCHAR(255),
  Price DECIMAL(10, 2)
);
GO

-- Tạo bảng BOOKING_FORM
CREATE TABLE BOOKING_FORM (
  BookingID INT PRIMARY KEY,
  CourtType NVARCHAR(50),
  OrderDate DATE,
  OrderTime TIME,
  StartTime DATETIME,
  EndTime DATETIME,
  Status NVARCHAR(20),
  CustomerID INT,
  SportCenterID INT,
  RID INT,
  FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID),
  FOREIGN KEY (SportCenterID) REFERENCES SPORT_CENTER(CenterID),
	FOREIGN KEY (RID) REFERENCES EMPLOYEE(EmployeeID)
);
GO

-- Tạo bảng MEMBER_CARD
CREATE TABLE MEMBER_CARD (
  CardID INT PRIMARY KEY,
  MembershipLevel NVARCHAR(50),
	CustomerID INT,
  FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID)
);
GO

-- Tạo bảng CANCEL_RULE
CREATE TABLE CANCEL_RULE (
    CanCelRuleID INT PRIMARY KEY,
    RuleName NVARCHAR(100),
    MinimumTime INT,
    TimeUnit NVARCHAR(20),
	PenaltyFee DECIMAL(10,2),
	MID INT,
	FOREIGN KEY (MID) REFERENCES EMPLOYEE(EmployeeID)
);
GO

-- Tạo bảng DISCOUNT
CREATE TABLE DISCOUNT (
  DiscountID INT PRIMARY KEY,
  DiscountName NVARCHAR(100),
  StartDate DATE,
  EndDate DATE,
	Pecentage DECIMAL(10,2),
	TargetUser NVARCHAR(255),
	MID INT,
	FOREIGN KEY (MID) REFERENCES EMPLOYEE(EmployeeID)
);
GO

--Tạo bảng PAYROLL
CREATE TABLE PAYROLL (
	PayrollID INT PRIMARY KEY,
	Month INT,
	Year INT,
	BasicSalary DECIMAL(10,2),
	Allowance DECIMAL(10,2),
	ShiftPay DECIMAL(10,2),
	SaleCommission DECIMAL(10,2),
	PenatyFee DECIMAL(10,2),
	EmployeeID INT,
	FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID)
);
GO
--Tạo bảng COURT_TYPE
CREATE TABLE COURT_TYPE (
	CourtType INT PRIMARY KEY,
	TypeofRental NVARCHAR(255)
);
GO

--Tạo bảng SPORT_COURT 
CREATE TABLE SPORT_COURT(
	CourtID INT PRIMARY KEY,
	CourtType INT,
	Capacity INT,
	UnitPrice DECIMAL(10,2),
	CenterID INT,
	FOREIGN KEY (CourtType) REFERENCES COURT_TYPE(CourtType),
	FOREIGN KEY (CenterID) REFERENCES SPORT_CENTER(CenterID)
);
GO

-- Tạo bảng INVOICE
CREATE TABLE INVOICE (
  InvoiceID INT PRIMARY KEY,
  RentTime DATETIME,
  TotalPrice DECIMAL(10, 2),
  PaymentMethod NVARCHAR(20),
	CreateTime DATETIME,
	Status NVARCHAR(50),
	BOOKINGID INT,
	DiscountID INT,
	CourtID INT,
	CID INT,
	FOREIGN KEY (BookingID) REFERENCES BOOKING_FORM(BookingID),
	FOREIGN KEY (CourtID) REFERENCES SPORT_COURT(CourtID),
	FOREIGN KEY (DiscountID) REFERENCES DISCOUNT(DiscountID),
	FOREIGN KEY (CID) REFERENCES EMPLOYEE(EmployeeID)
);
GO

-- Tạo bảng CANCELLATION_FORM
CREATE TABLE CANCELLATION_FORM (
  CancelFormID INT PRIMARY KEY,
  CancelTime DATETIME,
  PenaltyPrice DECIMAL(10, 2),
	Status NVARCHAR(50),
	CancelRuleID INT,
  BookingID INT,
	FOREIGN KEY (CancelRuleID) REFERENCES CANCEL_RULE(CancelRuleID),
  FOREIGN KEY (BookingID) REFERENCES BOOKING_FORM(BookingID)
);
GO

-- Tạo bảng SERVICE 
CREATE TABLE SERVICE (
	ServiceID INT PRIMARY KEY,
	ServiceName NVARCHAR(255),
	TimeUnitType NVARCHAR(255),
	Price DECIMAL(10,2),
	AvailableStatus NVARCHAR(50)
);
GO

-- Tạo bảng SERVICE_BOOKING
CREATE TABLE SERVICE_BOOKING (
	SBID INT PRIMARY KEY,
  BookingID INT,
  ServiceID INT,
  BookingQuantity INT,
  FOREIGN KEY (BookingID) REFERENCES BOOKING_FORM(BookingID),
	FOREIGN KEY (ServiceID) REFERENCES SERVICE(ServiceID)
);
GO

-- Tạo bảng PERSONAL_CLOSET
CREATE TABLE PERSONAL_CLOSET (
  PCServiceID INT PRIMARY KEY,
  ClosetID INT,
  StatusCloset NVARCHAR(50),
	FOREIGN KEY (PCServiceID) REFERENCES SERVICE(ServiceID)
);
GO

-- Tạo bảng RENTING_EQUIPMENT
CREATE TABLE RENTING_EQUIPMENT (
  REServiceID INT PRIMARY KEY,
  EquipmentType NVARCHAR(50),
  Quantity INT,
	FOREIGN KEY (REServiceID) REFERENCES SERVICE(ServiceID)
);
GO

-- Tạo bảng VIP_ROOM
CREATE TABLE VIP_ROOM (
  VRServiceID INT PRIMARY KEY,
  RoomID INT,
  StatusRoom NVARCHAR(50),
	FOREIGN KEY (VRServiceID) REFERENCES SERVICE(ServiceID)
);
GO

-- Tạo bảng RENTING_HLV
CREATE TABLE RENTING_HLV (
  RHServiceID INT PRIMARY KEY,
  Status NVARCHAR(50),
	Coach INT,
	FOREIGN KEY (RHServiceID) REFERENCES SERVICE(ServiceID)
);
GO
